# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temp.proto',
  package='temp',
  syntax='proto3',
  serialized_pb=b'\n\ntemp.proto\x12\x04temp\"i\n\nMapMessage\x12,\n\x06mapMsg\x18\x01 \x03(\x0b\x32\x1c.temp.MapMessage.MapMsgEntry\x1a-\n\x0bMapMsgEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x42\x06\xa2\x02\x03HLWb\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAPMESSAGE_MAPMSGENTRY = _descriptor.Descriptor(
  name='MapMsgEntry',
  full_name='temp.MapMessage.MapMsgEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='temp.MapMessage.MapMsgEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='temp.MapMessage.MapMsgEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=125,
)

_MAPMESSAGE = _descriptor.Descriptor(
  name='MapMessage',
  full_name='temp.MapMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mapMsg', full_name='temp.MapMessage.mapMsg', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MAPMESSAGE_MAPMSGENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=125,
)

_MAPMESSAGE_MAPMSGENTRY.containing_type = _MAPMESSAGE
_MAPMESSAGE.fields_by_name['mapMsg'].message_type = _MAPMESSAGE_MAPMSGENTRY
DESCRIPTOR.message_types_by_name['MapMessage'] = _MAPMESSAGE

MapMessage = _reflection.GeneratedProtocolMessageType('MapMessage', (_message.Message,), dict(

  MapMsgEntry = _reflection.GeneratedProtocolMessageType('MapMsgEntry', (_message.Message,), dict(
    DESCRIPTOR = _MAPMESSAGE_MAPMSGENTRY,
    __module__ = 'temp_pb2'
    # @@protoc_insertion_point(class_scope:temp.MapMessage.MapMsgEntry)
    ))
  ,
  DESCRIPTOR = _MAPMESSAGE,
  __module__ = 'temp_pb2'
  # @@protoc_insertion_point(class_scope:temp.MapMessage)
  ))
_sym_db.RegisterMessage(MapMessage)
_sym_db.RegisterMessage(MapMessage.MapMsgEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), b'\242\002\003HLW')
_MAPMESSAGE_MAPMSGENTRY.has_options = True
_MAPMESSAGE_MAPMSGENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001')
import abc
from grpc.beta import implementations as beta_implementations
from grpc.early_adopter import implementations as early_adopter_implementations
from grpc.framework.alpha import utilities as alpha_utilities
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
